defaultSelectedFields = [
    'id',
    'datetime',
    'security:analysis:triggeredmethods'
    ]

defaultFieldsLabels = ['hit_id',
                       'datetime',
                       'triggeredmethods'
                       ]

defaultParsedFields = []

defaultRulesScores = {'wutAutomatedSoftware': 8.0,
                      'firefoxAsChrome': 8.0,
                      'windowsAsLinux': 8.0,
                      'isDataCenterCdgGeneral': 8.0,
                      'x5PlayerWut': 8.0,
                      'chromeHeadLess': 8.0,
                      'ctmsBot': 8.0,
                      'appleVendorMismatch': 8.0,
                      'androidPltInDesktop': 8.0,
                      'invalidWglvDesktop': 8.0,
                      'isTinyWindowAndNotIframe': 8.0,
                      'oscpuWindowsAndFirefox': 8.0,
                      'cdgAndFirefox': 8.0,
                      'androidUAServerPlatform': 8.0,
                      'noOrientationAndSmartphone': 8.0,
                      'pltWindowsAndSmartphone': 8.0,
                      'pltMacOSAndSmartphone': 8.0,
                      'wglvBlacklistAndSmartphone': 8.0,
                      'isDataCenterCdg': 8.0,
                      'isPhantomBrowserCdg': 8.0,
                      'iosNotUsingSafari': 8.0,
                      'isDesktopVendor': 8.0,
                      'notChromeOnAndroid': 8.0,
                      'suspiciousDeviceSize': 8.0,
                      'nonStandardUserAgent': 8.0,
                      'noChromeCdg': 8.0,
                      'chromeNoHLS': 8.0,
                      'linuxIncorrectPlt': 8.0,
                      'invalidPlt': 8.0,
                      'invalidCxr': 8.0,
                      'invalidFirefox': 8.0,
                      'invalidRTT': 8.0,
                      'notificationsNotSupportedAndChromeMobile': 8.0,
                      'invalidTouchPointsAndMobile': 8.0,
                      'invalidMemoryAndCdgAndPlt': 8.0,
                      'fakeOpera': 8.0,
                      'androidWebkitAndPlt': 8.0,
                      'invalidMemoryHttps': 8.0,
                      'invalidChd': 8.0,
                      'reusedCodeVars': 8.0,
                      'fakeDZDevices': 8.0,
                      'invalidWglv': 8.0,
                      'wutMaliciousCode': 8.0,
                      'HeaderInjection': 8.0,
                      'BrowserDeviceOSTampering': 8.0,
                      'appPlayStoreRule': 2.0,
                      'Iframe': 7.0,
                      'abuse IP': 4.0,
                      'attacks IP': 6.0,
                      'malware IP': 8.0,
                      'Public proxy IP': 8.0,
                      'VPN proxy IP': 8.0,
                      'Web proxy': 8.0,
                      'Hosting/CDN proxy': 8.0,
                      'Tor proxy': 8.0,
                      'Opera Mini Proxy': 1.0,
                      'Google Proxy': 1.0,
                      'null user-agent': 8.0,
                      'OS tampering': 8.0,
                      'sdk user-agent': 8.0,
                      'UAAnalysis': 4.0,
                      'BrowserNameAnalysis': 8.0,
                      'OSNameAnalysis': 8.0,
                      'MSISDNInjectionRule': 8.0,
                      'TinyIframe': 8.0,
                      'AppPlayStoreRule': 2.0,
                      'Invalid App name': 8.0,
                      'msisdn header': 8.0,
                      'cdgChecker': 8.0,
                      'RepeatedUserRule': 0.0,
                      'CampaignFpCDRealtimeRule': 8.0,
                      'MalwareAPKRule': 8.0,
                      'invalidPrehit': 8.0,
                      'AdultKeywordsRule': 8.0,
                      'invalidChecksum': 8.0,
                      'invalidEHUA': 8.0,
                      'reverseCdg': 8.0,
                      'invalidSecurityData': 8.0,
                      'Hosting/CDN proxy IP': 8.0,
                      'pkFarm': 8.0,
                      'fakeJSCode': 8.0,
                      'SES IP': 1.0,
                      'Good Google Bot': 0.0
                      }
