defaultSelectedFields = [
    'id',
    'datetime',
    'visitor:device:type',
    'visitor:device:os:name',
    'visitor:device:os:type',
    'visitor:device:browser:name',
    'visitor:device:browser:version',
    'visitor:headers:User-Agent',
    'security:clientdata:ua',
    'visitor:headers:X-Requested-With',
    'visitor:headers:x-requested-with',
    'visitor:headers:Scheme',
    'visitor:network:geo:Country',
    'security:analysis:level',
    'security:clientdata:crx',
    'security:clientdata:aw',
    'security:clientdata:iw',
    'security:clientdata:wd',
    'security:clientdata:sf',
    'security:clientdata:oscpu',
    'security:clientdata:wut',
    'security:clientdata:ncd',
    'security:clientdata:ff',
    'security:clientdata:plt',
    'security:clientdata:cdg',
    'security:clientdata:nt',
    'security:clientdata:evln',
    'security:clientdata:dm',
    'security:clientdata:hls',
    'security:clientdata:mtp',
    'security:clientdata:rtt',
    'security:clientdata:dpr',
    'security:clientdata:wglv',
    'security:clientdata:vnd',
    'security:clientdata:ornt',
    'security:clientdata:ciu',
    'security:clientdata:klng',
    'security:clientdata:ctms',
    'security:clientdata:frm',
    'security:clientdata:ih',
    'security:ip:risks',
    'security',
    'security:clientdata:ver',
    'security:clientdata:ctm',
    'offer:advertiser:id',
    'visitor:device:browser:name',
    'security:clientdata:chd',
    'security:analysis:triggeredmethods',
    'security:clientdata:src',
    'offer:advertiser:type',
    'security:clientdata:lao',
    'security:clientdata:wnm',
    'visitor:headers',
    'visitor:headers:Via',
    'visitor:headers:Save-Data',
    'visitor:network:isp',
    'security:clientdata:proxy',
    'security:analysis:extras:cosname',
    'security:clientdata:cbrowsername',
    'security:clientdata:bad_code',
    'security:clientdata:keyset',
    'security:clientdata:phits',
    'security:clientdata:ehs',
    'visitor:site:url',
    'visitor:headers:Referer',
    'campaign:trafficsource:id',
    'visitor:site:macros:subpublisher_id'
    ]

defaultFieldsLabels = ['hit_id',
                       'datetime',
                       'device_type',
                       'device_osname',
                       'device_ostype',
                       'browser_name',
                       'browser_version',
                       'ua_headers',
                       'ua_security',
                       'X-Requested-With',
                       'X-Requested2',
                       'headers_Scheme',
                       'Country',
                       'analysis_level',
                       'crx',
                       'aw',
                       'iw',
                       'wd',
                       'sf',
                       'oscpu',
                       'wut',
                       'ncd',
                       'ff',
                       'plt',
                       'cdg',
                       'nt',
                       'evln',
                       'dm',
                       'hls',
                       'mtp',
                       'rtt',
                       'dpr',
                       'wglv',
                       'vnd',
                       'ornt',
                       'ciu',
                       'klng',
                       'ctms',
                       'frm',
                       'ih',
                       'ip_risk',
                       'security',
                       'ver',
                       'ctm',
                       'advertiserId',
                       'browser_name',
                       'chd',
                       'triggeredMethods',
                       'src',
                       'advertiser_type',
                       'lao',
                       'wnm',
                       'headers',
                       'via',
                       'save-data',
                       'isp',
                       'proxy',
                       'cosname',
                       'cbrowsername',
                       'bad_code',
                       'vars',
                       'phits',
                       'ehs',
                       'url',
                       'refUrl',
                       'trafficsource',
                       'subpublisher_id'
                       ]

defaultRulesScores = {'wutAutomatedSoftware': 8.0,
                      'firefoxAsChrome': 8.0,
                      'windowsAsLinux': 8.0,
                      'isDataCenterCdgGeneral': 8.0,
                      'x5PlayerWut': 8.0,
                      'chromeHeadLess': 8.0,
                      'ctmsBot': 8.0,
                      'appleVendorMismatch': 8.0,
                      'androidPltInDesktop': 8.0,
                      'invalidWglvDesktop': 8.0,
                      'isTinyWindowAndNotIframe': 8.0,
                      'oscpuWindowsAndFirefox': 8.0,
                      'cdgAndFirefox': 8.0,
                      'androidUAServerPlatform': 8.0,
                      'noOrientationAndSmartphone': 8.0,
                      'pltWindowsAndSmartphone': 8.0,
                      'pltMacOSAndSmartphone': 8.0,
                      'wglvBlacklistAndSmartphone': 8.0,
                      'isDataCenterCdg': 8.0,
                      'isPhantomBrowserCdg': 8.0,
                      'iosNotUsingSafari': 8.0,
                      'isDesktopVendor': 8.0,
                      'notChromeOnAndroid': 8.0,
                      'suspiciousDeviceSize': 8.0,
                      'nonStandardUserAgent': 8.0,
                      'noChromeCdg': 8.0,
                      'chromeNoHLS': 8.0,
                      'linuxIncorrectPlt': 8.0,
                      'invalidPlt': 8.0,
                      'invalidCxr': 8.0,
                      'invalidFirefox': 8.0,
                      'invalidRTT': 8.0,
                      'notificationsNotSupportedAndChromeMobile': 8.0,
                      'invalidTouchPointsAndMobile': 8.0,
                      'invalidMemoryAndCdgAndPlt': 8.0,
                      'fakeOpera': 8.0,
                      'androidWebkitAndPlt': 8.0,
                      'invalidMemoryHttps': 8.0,
                      'invalidChd': 8.0,
                      'reusedCodeVars': 8.0,
                      'fakeDZDevices': 8.0,
                      'invalidWglv': 8.0,
                      'wutMaliciousCode': 8.0,
                      'HeaderInjection': 8.0,
                      'BrowserDeviceOSTampering': 8.0,
                      'appPlayStoreRule': 2.0,
                      'Iframe': 7.0,
                      'abuse IP': 4.0,
                      'attacks IP': 6.0,
                      'malware IP': 8.0,
                      'Public proxy IP': 8.0,
                      'VPN proxy IP': 8.0,
                      'Web proxy': 8.0,
                      'Hosting/CDN proxy': 8.0,
                      'Tor proxy': 8.0,
                      'Opera Mini Proxy': 1.0,
                      'Google Proxy': 1.0,
                      'null user-agent': 8.0,
                      'OS tampering': 8.0,
                      'sdk user-agent': 8.0,
                      'UAAnalysis': 4.0,
                      'BrowserNameAnalysis': 8.0,
                      'OSNameAnalysis': 8.0,
                      'MSISDNInjectionRule': 8.0,
                      'TinyIframe': 8.0,
                      'AppPlayStoreRule': 2.0,
                      'Invalid App name': 8.0,
                      'msisdn header': 8.0,
                      'cdgChecker': 8.0,
                      'RepeatedUserRule': 0.0,
                      'CampaignFpCDRealtimeRule': 8.0,
                      'MalwareAPKRule': 8.0,
                      'invalidPrehit': 8.0,
                      'AdultKeywordsRule': 8.0,
                      'invalidChecksum': 8.0,
                      'invalidEHUA': 8.0,
                      'reverseCdg': 8.0,
                      'invalidSecurityData': 8.0,
                      'Hosting/CDN proxy IP': 8.0,
                      'pkFarm': 8.0,
                      'fakeJSCode': 8.0,
                      'SES IP': 1.0,
                      'Good Google Bot': 0.0
                      }