defaultSelectedFields = ['datetime', 
                         'security:analysis:level',
                         'security:clientdata:ncd',
                         'security:clientdata:tz', 
                         'security:clientdata:plt',
                         'security:clientdata:cntp', 
                         'visitor:headers:User-Agent',
]

defaultFieldsLabels = ['datetime',
                       'risk_level',
                       'network_speed',
                       'timezone',
                       'platform',
                       'connection_type',
                       'ua_headers',
]


defaultParsedFields = ['ua_product',
                       'ua_os',
                       'ua_platform',
                       'ua_productV',
                       'midnight_seconds',
                       'ua_wv']

defaultHotencFields = ['platform',
                       'connection_type',
                       'ua_product',
                       'ua_os',
                       'ua_platform',
                       'ua_productV',
                       'ua_wv']

defaultGtSelectedFields = ['datetime', 
                           'security:analysis:level',
                           'security:clientdata:ncd',
                           'security:clientdata:tz', 
                           'security:clientdata:plt',
                           'security:clientdata:cntp', 
                           'visitor:headers:User-Agent',
                           'security:clientdata:nt',
                           'security:clientdata:evln',
                           'security:clientdata:dm',
                           'security:clientdata:hls',
                           'security:clientdata:mtp',
                           'security:clientdata:rtt',
                           'security:clientdata:scd',
                           'security:clientdata:flv',
                           'security:clientdata:dpr',
                           'security:clientdata:spd',
                           'security:clientdata:wglv',
                           'security:clientdata:tch',
                           'security:clientdata:vnd',
                           'security:clientdata:ornt']

defaultGtFieldsLabels = ['datetime',
                         'risk_level',
                         'network_speed',
                         'timezone',
                         'platform',
                         'connection_type',
                         'ua_headers',
                         'nt',
                         'evln',
                         'dm',
                         'hls',
                         'mtp',
                         'rtt',
                         'scd',
                         'flv',
                         'dpr',
                         'spd',
                         'wglv',
                         'tch',
                         'vnd',
                         'ornt']


defaultGtParsedFields = ['ua_product',
                       'ua_os',
                       'ua_platform',
                       'ua_productV',
                       'midnight_seconds']

defaultGtHotencFields = ['platform',
                         'connection_type',
                         'ua_product',
                         'ua_os',
                         'ua_platform',
                         'ua_productV',
                         'nt',
                         'evln',
                         'dm',
                         'hls',
                         'mtp',
                         'rtt',
                         'scd',
                         'flv',
                         'dpr',
                         'spd',
                         'wglv',
                         'ornt',
]

